--- #YAML:1.0
name:                Email-Folder-IMAPS
version:             1.101
abstract:            Email::Folder Access to IMAP over SSL Folders
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Email::Folder::IMAP:           
    Email::FolderType::Net:        
    Net::IMAP::Simple::SSL:        1.3
    Test::More:                    0.47
    URI::imaps:                    
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casey West <casey@geeknest.com>
